language: objective-c
osx_image: xcode61

before_install: 

before_install:
- git submodule update --init --recursive
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild -project Seru/Seru.xcodeproj -scheme Seru build test | xcpretty -c; exit ${PIPESTATUS[0]}
