language: objective-c
osx_image: xcode61

before_install:
- git submodule update --init --recursive
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- brew install cathage
- carthage bootstrap

script:
- xcodebuild -project Seru.xcodeproj -scheme Seru build test | xcpretty -c; exit ${PIPESTATUS[0]}
