language: objective-c
osx_image: xcode7
podfile: Example/Podfile

cache: cocoapods

script:
- set -o pipefail
- xcodebuild test -workspace Example/SeruDemo.xcworkspace -scheme SeruDemo -sdk iphonesimulator | xcpretty -c
- pod lib lint --quick