language: objective-c
osx_image: xcode61
podfile: Test/Podfile

cache: cocoapods

before_install:
- gem install cocoapods --pre
#- git submodule update --init --recursive
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild test -workspace Seru.xcworkspace -scheme SeruTests | xcpretty -c
- pod lib lint --quick